//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BbungBbang.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BbungBbang.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap baseline_arrow_back_white_24dp {
            get {
                object obj = ResourceManager.GetObject("baseline_arrow_back_white_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Login_Btn_Login {
            get {
                return ResourceManager.GetString("String_Login_Btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계정명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Login_ID {
            get {
                return ResourceManager.GetString("String_Login_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램을 종료하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Login_Main_Msg_Exit {
            get {
                return ResourceManager.GetString("String_Login_Main_Msg_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호가 일치하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Login_Msg_Err_IncorrectPW {
            get {
                return ResourceManager.GetString("String_Login_Msg_Err_IncorrectPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호가 비어있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Login_Msg_Err_NonePW {
            get {
                return ResourceManager.GetString("String_Login_Msg_Err_NonePW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경고과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Login_Msg_Warning {
            get {
                return ResourceManager.GetString("String_Login_Msg_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Login_PW {
            get {
                return ResourceManager.GetString("String_Login_PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Login_Title {
            get {
                return ResourceManager.GetString("String_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오전과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Time_AM {
            get {
                return ResourceManager.GetString("String_Time_AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오후과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string String_Time_PM {
            get {
                return ResourceManager.GetString("String_Time_PM", resourceCulture);
            }
        }
    }
}
